src/Entity/Movie.php
<?php

namespace App\Entity;

use App\Repository\MovieRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MovieRepository::class)]
class Movie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 127)]
    private ?string $title = null;

    #[ORM\Column(length: 63)]
    private ?string $director = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $release_date = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $overview = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDirector(): ?string
    {
        return $this->director;
    }

    public function setDirector(string $director): static
    {
        $this->director = $director;

        return $this;
    }

    public function getReleaseDate(): ?int
    {
        return $this->release_date;
    }

    public function setReleaseDate(int $release_date): static
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getOverview(): ?string
    {
        return $this->overview;
    }

    public function setOverview(string $overview): static
    {
        $this->overview = $overview;

        return $this;
    }
}

src/Form/SearchType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SearchType as SearchDefaultType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('query', SearchDefaultType::class, )
            ->add('submit', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Movie;
use App\Form\SearchType;
use Doctrine\DBAL\Exception;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Exception\ORMException;
use Knp\Component\Pager\PaginatorInterface;
use Psr\Cache\InvalidArgumentException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Cache\Adapter\FilesystemAdapter;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Contracts\Cache\ItemInterface;

class MainController extends AbstractController
{
    /**
     * Direct call to TMDB API that returns the data to the homepage view
     *
     * @param EntityManagerInterface $entityManager
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     * @throws InvalidArgumentException
     */
    #[Route('/', name: 'home_page', methods: ['GET'])]
    public function homePage(
        EntityManagerInterface $entityManager,
        Request $request,
        PaginatorInterface $paginator
    ): Response
    {
        return $this->getHomepageView($request, $entityManager, $paginator);
    }

    /**
     * Renders the detailed page of a specific movie with a given ID
     *
     * @param int $id
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    #[Route('/movie/{id}', name: 'movie_detailed')]
    public function showById(int $id, EntityManagerInterface $entityManager): Response
    {
        $cache = new FilesystemAdapter();

        try {
            $response = $cache->get($id, function (ItemInterface $item) use ($entityManager, $id) {

                //set expiry to 30min
                $item->expiresAfter(1800);

                //return movie with the specific id
                return $entityManager->getRepository(Movie::class)->getMovieById($id);
            });

            return $this->render('main/detail_page.html.twig', [
                'movie' => $response,
            ]);

        } catch (Exception | ORMException | InvalidArgumentException $exception) {

            return new Response('Query failed: '.$exception->getMessage(), 500);
        }
    }


    /**
     * runs search and renders results
     *
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @param string $term
     * @return Response
     */
    #[Route('/search', name: 'search_movies')]
    public function search(Request $request, EntityManagerInterface $entityManager, PaginatorInterface $paginator): Response
    {
        $form = $this->createForm(SearchType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Get the search term from the request
            $searchTerm = $request->request->all();
//            dd($searchTerm['search']);
            // Redirect to the route that displays the search results
            return $this->redirectToRoute('search_results', $searchTerm);
        }
        try {
            return $this->getHomepageView($request, $entityManager, $paginator);

        } catch (InvalidArgumentException $e) {

            return new Response('Query failed: '.$e->getMessage(), 500);
        }
    }

    /**
     * return a view of the search results queried from search form
     *
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @param PaginatorInterface $paginator
     * @return Response
     */
    #[Route('/search-results', name: 'search_results')]
    public function searchResults(Request $request, EntityManagerInterface$entityManager, PaginatorInterface $paginator): Response
    {

        $cache = new FilesystemAdapter();
        $form = $this->createForm(SearchType::class);

        $searchTerm = $request->query->all()['search']['query'];

        // dd($searchTerm['search']['query']); //access searchterm
        // Perform search operation using the $searchTerm
        try {
            $response = $cache->get($searchTerm, function (ItemInterface $item) use ($entityManager, $searchTerm, $paginator) {

                //set expiry to 30min
                $item->expiresAfter(1800);
                $query = $entityManager->getRepository(Movie::class)->getMoviesWithTermQueryBuilder($searchTerm);

                //paginate with query
                return $paginator->paginate(
                    $query,
                    1,
                    10
                );
            });
        } catch (Exception|ORMException|InvalidArgumentException $exception) {
            return new Response('Query failed: ' . $exception->getMessage(), 500);

        }

        return $this->render('main/homepage.html.twig', [
            'pagination' => $response,
            'form' => $form
        ]);
    }

    /**
     * returns a twig render response depending on the list of movies that need to be rendered
     *
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @param PaginatorInterface $paginator
     * @return Response
     * @throws InvalidArgumentException
     */
    public function getHomepageView(Request $request, EntityManagerInterface $entityManager, PaginatorInterface $paginator): Response
    {
        $cache = new FilesystemAdapter();
        $form = $this->createForm(SearchType::class);

        // cacheKey is also the page number for paginator
        $cacheKey = $request->query->getInt('page', 1);

        // caching response for increased performance/reduced TMDB calls
        $pagination = $cache->get('page' . $cacheKey, function (ItemInterface $item) use ($entityManager, $paginator, $cacheKey) {

            // expires after 30 minutes
            $item->expiresAfter(1800);

            try {

                //create query that queries the movies from database
                $query = $entityManager->getRepository(Movie::class)->getWithQueryBuilder();

                //paginate with query
                $pagination = $paginator->paginate(
                    $query,
                    $cacheKey,
                    10
                );

            } catch (Exception|ORMException|InvalidArgumentException $e) {
                return new Response('Query failed: ' . $e->getMessage(), 500);
            }

            return $pagination;
        });

        return $this->render('main/homepage.html.twig', [
            'pagination' => $pagination,
            'form' => $form
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}YAMDB{% endblock %}</title>
        <link rel="icon" type="image/png" sizes="192x192"  href="{{ asset('IO_Icon.png') }}">
        {% block stylesheets %}
            <!-- Customized Bootstrap Stylesheet -->
            <link href="{{ asset('../assets/styles/bootstrap.min.css') }}" rel="stylesheet">

            <!-- Template Stylesheet -->
            <link href="{{ asset('../assets/styles/app.css') }}" rel="stylesheet">
        {% endblock %}

        {% block javascripts %}
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="{{ path('home_page') }}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
            <svg class="book-logo" width="5" height="5">
                <img class="book-logo" src="{{ asset('noun-book-1055719.svg') }}" alt="logo book">
            </svg>
            <span class="fs-4">YAMDB</span>
        </a>

        <ul class="nav nav-pills">
            <li class="nav-item"><a
                        href="{{ path('home_page') }}"
                        class="nav-link{% if app.request.attributes.get('_route') is same as 'home_page' %} active{% endif %}"
                        aria-current="{% if app.current_route is same as 'home_page' %}page{% endif %}">Home</a></li>
        </ul>
    </header>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/main/detail_page.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h1>{{ movie.title }}</h1>
    <div class="d-flex flex-row flex-lg-row justify-content-between">
        <p class="fw-bold">{{ movie.releaseDate }}</p>
        <p>Directed by {{ movie.director }}</p>
    </div>
<p class="pretty-wrap"><span>Plot</span> <br>{{ movie.overview }}</p>
{% endblock %}

templates/main/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{ include('main/table_with_pagination.html.twig') }}
    {{ include('main/searchbar.html.twig') }}

{% endblock %}

templates/main/paginator.html.twig
<div class="paginator">
    {{ knp_pagination_render(pagination) }}
</div>

templates/main/searchbar.html.twig
{% block search %}

    <!-- search bar -->
    <div class="temp">
        <div class="col-md-6">
            {{ form_start(form, {'attr': {'action': path('search_movies'), 'method': 'GET'}}) }} {# Specify route and method for form submission #}
            <div class="form">
                <i class="fa fa-search"></i>
                {{ form_widget(form.query, { 'attr': {'class': 'form-control form-input', 'placeholder': 'Search anything...'} }) }} {# Render the search input field #}
                <span class="left-pan">{{ form_row(form.submit, {'label': 'Search', 'attr': {'class': 'btn btn-light'}}) }}</span> {# Render the submit button #}
                <div class="alert disabled">{{ form_errors(form.query) }}</div> {# Render errors for the search field #}
            </div>
            {{ form_end(form) }} {# End the form #}
        </div>
    </div>

{% endblock %}

templates/main/table.html.twig
<!-- table content -->
<div class="col-sm-12 col-xxl-10">
    <div class="bg-light rounded h-200 p-4">
        <h5 class="mb-4"><span>YAMDB:</span> Yet Another Movie Database</h5>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Director</th>
                <th scope="col">Year produced</th>
            </tr>
            </thead>
            <tbody>

            {% for movie in movies %}

                <tr>
                    <th scope="row">{{ loop.index }}</th>
                    <td class="fw-bold">{{  movie.title }}</td>
                    <td>{{ movie.director }}</td>
                    <td>{{ movie.releaseDate }}</td>
                </tr>

            {% endfor %}

            </tbody>
        </table>
    </div>
</div>

templates/main/table_with_pagination.html.twig
<!-- table content -->
<div class="col-sm-12 col-xxl-10">
    <div class="bg-light rounded h-200">
        {{ include('main/paginator.html.twig') }}
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Director</th>
                <th scope="col">Year produced</th>
            </tr>
            </thead>
            <tbody>

            {% for movie in pagination %}

                <tr onclick="window.location='{{ path('movie_detailed', {id: movie.id}) }}';">
                        <th scope="row">{{ movie.id }}</th>
                        <td class="fw-bold">{{  movie.title }}</td>
                        <td>{{ movie.director }}</td>
                        <td>{{ movie.releaseDate }}</td>
                </tr>

            {% endfor %}

            </tbody>
        </table>
    </div>
</div>

templates/package/knp_paginator_links.html.twig
{#
TODO: change pagination template
#}